apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-blackbox-conf
  labels:
    name: prometheus-blackbox-conf
  namespace: {{ .Values.namespace }}
data:
  {{- $file := .Files }}
  {{- range $path, $byte := .Files.Glob "confs/prometheus/blackbox_exporter/*" }}
  {{- $list := $path | splitList "/"}}
  {{- $length := len $list }}
  {{- $last := add $length -1 }}
  {{ index $list $last }}: |-
    {{- range $file.Lines $path }}
      {{ . }}
    {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: {{ .Values.namespace }}
data:
  {{- $file := .Files }}
  {{- range $path, $byte := .Files.Glob "confs/prometheus/server/*" }}
  {{- $list := $path | splitList "/"}}
  {{- $length := len $list }}
  {{- $last := add $length -1 }}
  {{ index $list $last }}: |-
    {{- range $file.Lines $path }}
      {{ . }}
    {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: prometheus-server
  ports:
  - name: metricsport
    protocol: TCP
    port: 9090
    targetPort: 9090
  - name: blackboxport
    protocol: TCP
    port: 9115
    targetPort: 9115
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.serverimage }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            limits:
             memory: {{ .Values.prometheus.resources.server_limit_memory }}
             cpu: {{ .Values.prometheus.resources.server_limit_cpu }}
            requests:
             memory: {{ .Values.prometheus.resources.server_request_memory }}
             cpu: {{ .Values.prometheus.resources.server_request_cpu }}
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/prometheus.rules
              subPath: prometheus.rules
            - name: prometheus-storage-volume
              mountPath: /prometheus/
        - name: prometheus-blackbox-exporter
          image: {{ .Values.prometheus.blackboximage }}
          ports:
            - containerPort: 9115
          resources:
            limits:
             memory: {{ .Values.prometheus.resources.exporter_limit_memory }}
             cpu: {{ .Values.prometheus.resources.exporter_limit_cpu }}
            requests:
             memory: {{ .Values.prometheus.resources.exporter_request_memory }}
             cpu: {{ .Values.prometheus.resources.exporter_request_cpu }}
          volumeMounts:
            - name: prometheus-blackbox-volume
              mountPath: /etc/blackbox_exporter/config.yml
              subPath: config.yml
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          emptyDir: {}
        - name: prometheus-blackbox-volume
          configMap:
            name: prometheus-blackbox-conf
